/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;
import Controlador.BD_cargo;
import Entidades.Validaciones;
import Entidades.cargo;
import Reportes.Global;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author samux
 */
public class frmCargo extends javax.swing.JFrame {

    /**
     * Creates new form frmClientes
     */
    public frmCargo() {
        initComponents();
        this.setLocationRelativeTo(null);
        noMostrarDatosEmplado();
        mostrar("");
        inhabilitar();
    }
    
    void noMostrarDatosEmplado() {
        lblCodigo.setVisible(false);
        lblTipoUser.setVisible(false);
        lblNombre.setVisible(false);
        lblApellidos.setVisible(false);
    }
    
    
    Validaciones  validaciones = new Validaciones();
    private String accion = "guardar";
    
    void inhabilitar() {
        txtCod_cargo.setEnabled(false);
        txtNombre_cargo.setEnabled(false);
        txtSueldo.setEnabled(false);
  
        
        btnGuardar.setEnabled(false);
        btnCancelar.setEnabled(false);
        btnEliminar.setEnabled(false);
        txtCod_cargo.setText("");
        txtNombre_cargo.setText("");
        txtSueldo.setText("");


    }
    
    void habilitar() {
        txtCod_cargo.setEnabled(false);
        txtNombre_cargo.setEnabled(true);
        txtSueldo.setEnabled(true);
        btnGuardar.setEnabled(true);
        btnCancelar.setEnabled(true);
        btnEliminar.setEnabled(true);
        txtCod_cargo.setText("");
        txtNombre_cargo.setText("");
        txtSueldo.setText("");
    }

    void mostrar(String buscar) {
        try {
            DefaultTableModel modelo;
            
            BD_cargo func = new BD_cargo();
            modelo = func.mostrar(buscar);
            
            tablalistado.setModel(modelo);
            //lbltotalregistros.setText("Total Registros " + Integer.toString(func.totalregistros));
        } 
        catch (Exception e) {
            JOptionPane.showConfirmDialog(null, "Error al acceder a los datos desde la base de datos");
        }
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelUser = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        txtNombre_cargo = new javax.swing.JTextField();
        txtSueldo = new javax.swing.JTextField();
        txtCod_cargo = new javax.swing.JTextField();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        panelAtras = new javax.swing.JPanel();
        lblBack = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblCerrar = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        btnEliminar = new javax.swing.JButton();
        btnReporte = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablalistado = new javax.swing.JTable();
        lblCodigo = new javax.swing.JLabel();
        lblTipoUser = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblApellidos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelUser.setBackground(new java.awt.Color(51, 153, 255));
        panelUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/Imagenes Menu Cargo/icons8_Road_Construction_100px_1.png"))); // NOI18N
        panelUser.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 100, 100));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Código:");
        panelUser.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 60, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nombre:");
        panelUser.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 70, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Sueldo");
        panelUser.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 70, -1));
        panelUser.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 180, 10));
        panelUser.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 180, 10));
        panelUser.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 180, 10));

        txtNombre_cargo.setBackground(new java.awt.Color(51, 153, 255));
        txtNombre_cargo.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        txtNombre_cargo.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre_cargo.setToolTipText("Ingrese cédula o RUC");
        txtNombre_cargo.setBorder(null);
        txtNombre_cargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombre_cargoActionPerformed(evt);
            }
        });
        panelUser.add(txtNombre_cargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 180, -1));

        txtSueldo.setBackground(new java.awt.Color(51, 153, 255));
        txtSueldo.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        txtSueldo.setForeground(new java.awt.Color(255, 255, 255));
        txtSueldo.setToolTipText("Ingrese Nombres");
        txtSueldo.setBorder(null);
        txtSueldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSueldoActionPerformed(evt);
            }
        });
        panelUser.add(txtSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 180, -1));

        txtCod_cargo.setBackground(new java.awt.Color(51, 153, 255));
        txtCod_cargo.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        txtCod_cargo.setForeground(new java.awt.Color(255, 255, 255));
        txtCod_cargo.setBorder(null);
        txtCod_cargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCod_cargoActionPerformed(evt);
            }
        });
        panelUser.add(txtCod_cargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 180, -1));

        btnNuevo.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/Imagenes Menu Cliente/icons8_Add_User_Male_16px.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.setToolTipText("Agregar un nuevo cliente");
        btnNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        panelUser.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 90, -1));

        btnGuardar.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/Imagenes Menu Cliente/icons8_Save_16px.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setToolTipText("Guardar/Editar un cliente");
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        panelUser.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, -1));

        btnCancelar.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/Imagenes Menu Cliente/icons8_Cancel_16px.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setToolTipText("Salir ");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        panelUser.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 100, -1));

        panelAtras.setBackground(new java.awt.Color(0, 102, 204));
        panelAtras.setToolTipText("Regresar");
        panelAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblBack.setBackground(new java.awt.Color(255, 51, 51));
        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/Imagenes Menu Princpal/icons8_Left_40px.png"))); // NOI18N

        javax.swing.GroupLayout panelAtrasLayout = new javax.swing.GroupLayout(panelAtras);
        panelAtras.setLayout(panelAtrasLayout);
        panelAtrasLayout.setHorizontalGroup(
            panelAtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAtrasLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblBack))
        );
        panelAtrasLayout.setVerticalGroup(
            panelAtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAtrasLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblBack))
        );

        panelUser.add(panelAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel1.setText("Cargo");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, 30));

        lblCerrar.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        lblCerrar.setText("x");
        lblCerrar.setToolTipText("Salir");
        lblCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
        });
        jPanel1.add(lblCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, -1, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/Imagenes Menu Cliente/icons8_Search_24px.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 360, 10));

        btnEliminar.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/Imagenes Menu Cliente/icons8_Delete_16px.png"))); // NOI18N
        btnEliminar.setText("Eliminar Cargo");
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, -1, -1));

        btnReporte.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        btnReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/Imagenes Menu Cliente/icons8_Report_Card_16px.png"))); // NOI18N
        btnReporte.setText("Reporte");
        btnReporte.setToolTipText("Ver Listado de clientes");
        btnReporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });
        jPanel1.add(btnReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, -1, -1));

        txtBuscar.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        txtBuscar.setText("Buscar por codigo o por Nombre");
        txtBuscar.setToolTipText("Buscar Clientes por cédula o RUC");
        txtBuscar.setBorder(null);
        txtBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBuscarMouseClicked(evt);
            }
        });
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });
        jPanel1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 360, -1));

        tablalistado = new javax.swing.JTable(){
            public boolean isCellEditable(int x,int y){
                return false;
            }
        };
        tablalistado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablalistado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tablalistado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablalistadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablalistado);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 640, 240));

        lblCodigo.setText("Cod");
        jPanel1.add(lblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        lblTipoUser.setText("Tipo");
        jPanel1.add(lblTipoUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        lblNombre.setText("Nombre");
        jPanel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, -1, -1));

        lblApellidos.setText("Apellidos");
        jPanel1.add(lblApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelUser, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelUser, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_lblCerrarMouseClicked

    private void tablalistadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablalistadoMouseClicked
        // TODO add your handling code here:
        btnGuardar.setText("Editar");
        habilitar();
        btnEliminar.setEnabled(true);
        accion = "editar";
        
        int fila = tablalistado.rowAtPoint(evt.getPoint());
        
        txtCod_cargo.setText(tablalistado.getValueAt(fila, 0).toString());
        txtNombre_cargo.setText(tablalistado.getValueAt(fila, 1).toString());
        txtSueldo.setText(tablalistado.getValueAt(fila, 2).toString());
    }//GEN-LAST:event_tablalistadoMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        if(!txtCod_cargo.getText().equals("")) {
            int confirmacion = JOptionPane.showConfirmDialog(rootPane, "Estas seguro de Eliminar el cargo?", "Confirmar", 2);
            if(confirmacion == 0) {
                BD_cargo func = new BD_cargo();
cargo dts = new cargo();

                dts.setCod_cargo(Integer.parseInt(txtCod_cargo.getText()));
                func.eliminar(dts.getCod_cargo());
                mostrar("");
                inhabilitar();
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        // TODO add your handling code here:
        mostrar(txtBuscar.getText());
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void txtBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscarMouseClicked
        // TODO add your handling code here:
        txtBuscar.setText("");
    }//GEN-LAST:event_txtBuscarMouseClicked

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        //Validacion de que se deben llenar los regitros principales

        if(txtNombre_cargo.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar la cedula o RUC");
            txtNombre_cargo.requestFocus();
            return;
        }

        if(txtSueldo.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar el nombre del cargo");
            txtSueldo.requestFocus();
            return;
        }
        //Almacenamiento de los datos
        //se crea un cliente nuevo
cargo c1 = new cargo();
        //se crea la clase de conexion a la base de datos
        BD_cargo bd = new BD_cargo();

        //llenado de datos
        c1.setNombre_cargo(txtNombre_cargo.getText());
              c1.setSueldo(Double.parseDouble(txtSueldo.getText()));
               //Para guardar un nuevo cliente
        if(accion.equals("guardar")) {
            if(bd.insertar(c1)) {
                JOptionPane.showMessageDialog(rootPane, "El cargo fue registrado satisfactoriamente");
                mostrar("");
                inhabilitar();
            }
        }

        //para editar un cliente existente
        else if(accion.equals("editar")) {
            c1.setCod_cargo(Integer.parseInt(txtCod_cargo.getText()));

            if(bd.editar(c1)) {
                JOptionPane.showMessageDialog(rootPane, "El cargo fue editado satisfactoriamente");
                mostrar("");
                inhabilitar();
            }
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        habilitar();
        btnGuardar.setText("Guardar");
        accion = "guardar";
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void txtCod_cargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCod_cargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCod_cargoActionPerformed

    private void txtSueldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSueldoActionPerformed
        // TODO add your handling code here:
        txtSueldo.transferFocus();
    }//GEN-LAST:event_txtSueldoActionPerformed

    private void txtNombre_cargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombre_cargoActionPerformed
        // TODO add your handling code here:
        txtNombre_cargo.transferFocus();
    }//GEN-LAST:event_txtNombre_cargoActionPerformed

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        // TODO add your handling code here:
        
        try {
            String cad="cargos";
            //agregar parametros al reporte
            Map<String, Object> params = new HashMap<String, Object>();
            params.put("cargos", cad);
            Global.generarReporte("rptCargos",params);
        } catch (Exception ex) { }
    }//GEN-LAST:event_btnReporteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCargo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnReporte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator9;
    public javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblCerrar;
    public javax.swing.JLabel lblCodigo;
    public javax.swing.JLabel lblNombre;
    public javax.swing.JLabel lblTipoUser;
    private javax.swing.JPanel panelAtras;
    private javax.swing.JPanel panelUser;
    private javax.swing.JTable tablalistado;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCod_cargo;
    private javax.swing.JTextField txtNombre_cargo;
    private javax.swing.JTextField txtSueldo;
    // End of variables declaration//GEN-END:variables
}
