/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author Samuel Isaias Calderon Aguirre
 */
public class frmContratoRep extends javax.swing.JFrame {

    /**
     * Creates new form frmInventario
     */
    public frmContratoRep() {
        initComponents();
        this.setLocationRelativeTo(null);
        noMostrarDatosEmplado();
    }

     void regresarMenuAnterior() {
        frmInicio frm =  new frmInicio();
        frm.lblCodigoEmp.setText(lblCodigo.getText());
        frm.lblCargo.setText(lblTipoUser.getText());
        frm.lblNombres.setText(lblNombre.getText());
        frm.lblApellidos.setText(lblApellidos.getText());
        this.dispose();
        frm.setVisible(true);
        frm.toFront();
    }
     
     void noMostrarDatosEmplado() {
        lblCodigo.setVisible(false);
        lblTipoUser.setVisible(false);
        lblNombre.setVisible(false);
        lblApellidos.setVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblCerrar = new javax.swing.JLabel();
        panelProductos = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        panelMarcas = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        panelAtras = new javax.swing.JPanel();
        lblBack = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        lblTipoUser = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblApellidos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/Imagenes Menu Proveedores/icons8_Inventory_Flow_24px.png"))); // NOI18N
        jLabel1.setText("  Control de Contratos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 250, 30));

        lblCerrar.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        lblCerrar.setForeground(new java.awt.Color(255, 255, 255));
        lblCerrar.setText("x");
        lblCerrar.setToolTipText("Salir");
        lblCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
        });
        jPanel1.add(lblCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 20, 30));

        panelProductos.setToolTipText("Iniciar una nueva solicitud");
        panelProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelProductosMouseClicked(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/Imagenes Menu Princpal/icons8_New_Copy_80px_1.png"))); // NOI18N

        jLabel16.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 153, 255));
        jLabel16.setText("Iniciar una nueva solicitud ");

        javax.swing.GroupLayout panelProductosLayout = new javax.swing.GroupLayout(panelProductos);
        panelProductos.setLayout(panelProductosLayout);
        panelProductosLayout.setHorizontalGroup(
            panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProductosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(88, 88, 88))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProductosLayout.createSequentialGroup()
                .addGap(0, 45, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelProductosLayout.setVerticalGroup(
            panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addGap(9, 9, 9))
        );

        jPanel1.add(panelProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 260, 120));

        panelMarcas.setToolTipText("Control de contratos");
        panelMarcas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelMarcas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelMarcasMouseClicked(evt);
            }
        });

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/Imagenes Menu Princpal/icons8_Documents_80px.png"))); // NOI18N

        jLabel20.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 153, 255));
        jLabel20.setText("Control de contratos");

        javax.swing.GroupLayout panelMarcasLayout = new javax.swing.GroupLayout(panelMarcas);
        panelMarcas.setLayout(panelMarcasLayout);
        panelMarcasLayout.setHorizontalGroup(
            panelMarcasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMarcasLayout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(panelMarcasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMarcasLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(87, 87, 87))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMarcasLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(51, 51, 51))))
        );
        panelMarcasLayout.setVerticalGroup(
            panelMarcasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMarcasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addGap(9, 9, 9))
        );

        jPanel1.add(panelMarcas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 260, 120));

        panelAtras.setBackground(new java.awt.Color(51, 153, 255));
        panelAtras.setToolTipText("Regresar");
        panelAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblBack.setBackground(new java.awt.Color(255, 51, 51));
        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/Imagenes Menu Princpal/icons8_Left_40px.png"))); // NOI18N
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelAtrasLayout = new javax.swing.GroupLayout(panelAtras);
        panelAtras.setLayout(panelAtrasLayout);
        panelAtrasLayout.setHorizontalGroup(
            panelAtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAtrasLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblBack))
        );
        panelAtrasLayout.setVerticalGroup(
            panelAtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAtrasLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblBack))
        );

        jPanel1.add(panelAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        lblCodigo.setText("Cod");
        jPanel1.add(lblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        lblTipoUser.setText("Tipo");
        jPanel1.add(lblTipoUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, -1));

        lblNombre.setText("Nombre");
        jPanel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, -1, -1));

        lblApellidos.setText("Apellidos");
        jPanel1.add(lblApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_lblCerrarMouseClicked

    private void panelProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelProductosMouseClicked
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(null, "Hola");
        /**
        frmClientes frm = new frmClientes();
        frm.setVisible(true);
        frm.toFront();
        * **/
        
        frmSolicitudReparacion frm = new frmSolicitudReparacion();
        //frm.setModalExclusionType(Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        frm.lblCodigo.setText(lblCodigo.getText());
        frm.lblTipoUser.setText(lblTipoUser.getText());
        frm.lblNombre.setText(lblNombre.getText());
        frm.lblApellidos.setText(lblApellidos.getText());
        frm.lblCodigoUser.setText(lblCodigo.getText());
        frm.lblUser.setText(lblNombre.getText() + " " + lblApellidos.getText());
        this.dispose();
        frm.setVisible(true);
        frm.toFront();
    }//GEN-LAST:event_panelProductosMouseClicked

    private void panelMarcasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMarcasMouseClicked
        // TODO add your handling code here:
        frmControlContratos frm = new frmControlContratos();
        //frm.setModalExclusionType(Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        frm.lblCodigo.setText(lblCodigo.getText());
        frm.lblTipoUser.setText(lblTipoUser.getText());
        frm.lblNombre.setText(lblNombre.getText());
        frm.lblApellidos.setText(lblApellidos.getText());
        frm.lblCodigoUser.setText(lblCodigo.getText());
        frm.lblUser.setText(lblNombre.getText() + " " + lblApellidos.getText());
        this.dispose();
        frm.setVisible(true);
        frm.toFront();
    }//GEN-LAST:event_panelMarcasMouseClicked

    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        // TODO add your handling code here:
        regresarMenuAnterior();
    }//GEN-LAST:event_lblBackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmContratoRep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmContratoRep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmContratoRep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmContratoRep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmContratoRep().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblCerrar;
    public javax.swing.JLabel lblCodigo;
    public javax.swing.JLabel lblNombre;
    public javax.swing.JLabel lblTipoUser;
    private javax.swing.JPanel panelAtras;
    public javax.swing.JPanel panelMarcas;
    public javax.swing.JPanel panelProductos;
    // End of variables declaration//GEN-END:variables
}
